### ISSUE TITLE
Elasticsearch pull of bro data?

### ISSUE THREAD

**Issue by SMAPPER** [ocmdev/rita#44] opened 2017-03-30 15:05 UTC
Any chance this project will later have a feature to pull the Bro logs directly from Elasticsearch rather than from files? I thought a previous version of RITA did just this but I may be mistaken.

I would love to incorporate this in use cases where individuals are collecting bro logs with ELK and then use RITA to analyze them.

**Comment by JonZeolla** [comment] 2017-03-30 19:22
This would be very interesting for me as well.  I have a ton of my bro logs in ES - but I think I recall someone mentioning they moved away from that on purpose

**Comment by bstlee0** [comment] 2017-04-03 17:25
Hey JonZeolla, you are correct.  I believe John Stand said on an webinar that ELK doesn't handle Select statements correctly.

**Comment by JonZeolla** [comment] 2017-04-03 17:28
I thought his comments were related to ES scaling, but he may have made multiple comments on the topic.  Anyway, that's a bit confusing to me, because my ES environment is handling quite a bit of scale, so I'm sure there are some more details that need to be considered.

**Comment by Zalgo2462** [comment] 2017-04-03 20:25
The possibility of writing parsers to pull in data from ELK, redis, kafka, etc. exists. At the end of the day we need to populate the data structures here: https://github.com/ocmdev/rita/tree/master/parser. 

Elasticsearch was used in a previous iteration of RITA; however, the domain specific language for Elasticsearch can be unwieldy at times. However, it should be possible to get RITA to import data from any number of sources and store it in MongoDB. Unfortunately, this means yet another copy of the data will be created (on MongoDB).

**Comment by strandjs** [comment] 2017-05-09 09:45
The issue is that ES is great for unstructured data and retrieving that data in weird ways.  However, we we do analysis like "pull every connection for the past 24 hours and sort it in x way."  It tends to tip over at about 1.5 billion records.  

If someone wants to write a module to pull data into Mongo that would be quite awesome.  We will add it to the list and get to it a bit later.

**Comment by ethack** [comment] 2017-12-14 22:49
Closing in favor of https://github.com/ocmdev/rita/issues/146 and research into https://www.elastic.co/guide/en/logstash/current/plugins-outputs-mongodb.html

**Closed by ethack** 2017-12-14 22:49 UTC
Labels: Type: Enhancement
